name: Android CI

on:
  # push:
  #  branches: [ "master" ]
  # pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Run Build Project
    - name: Build with Gradle
    #  run: ./gradlew app:assembleFullRelease
      run: ./gradlew wear:assembleFullRelease

    # Sign APK File
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: wear/build/outputs/apk/full/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      
    # Upload Artifact Build
    - name: Upload Logfiles
      uses: actions/upload-artifact@v4
      with:
         name: 'Build Logfiles'
         path: |
             app/build/**
             wear/build/**
         # path: wear/build/**
